### ISSUE TITLE
Api Controller를 사용하기보다, 별도 module 별로 controller를 구성하고 router module을 구성해서 사용하면 어떨까요?

### ISSUE THREAD

**Issue by ammerss** [TEAM-LEG3ND/studium-server#13]
Api Controller를 사용하기보다, 별도 module 별로 controller를 구성하고 router module을 구성해서 사용하면 어떨까요?
https://docs.nestjs.com/recipes/router-module

_Originally posted by @d0lim in https://github.com/TEAM-LEG3ND/studium-server/pull/12#discussion_r1226780015_

**Comment by redjen8** [comment]
https://docs.nestjs.com/recipes/router-module#:~:text=This%20feature%20should%20be%20used%20very%20carefully%2C%20as%20overusing%20it%20can%20make%20code%20difficult%20to%20maintain%20over%20time.

언급되어 있듯이 주의하여 사용해야 할 피쳐이긴 하지만~
도메인 별로 api를 분리하고, 그에 맞는 정책을 적용하기에는 알맞은 기능이라고 생각됩니다. 도입되면 좋겠네요

**Comment by selgyun** [comment]
#15 개발 전에 api controller를 삭제하는 브랜치를 생성하도록 하겠습니다. 그러면 연경님과 제가 따로 각 모듈을 독립적으로 개발할 수 있는 환경이 만들어질 수 있어서 좋을 것 같아요!

**Comment by selgyun** [comment]
이슈 종료하겠습니다.
