### ISSUE TITLE
CORS allow all 정책 추가

### ISSUE THREAD

**Issue by redjen8** [TEAM-LEG3ND/studium-server#59]
## 개요
프론트 개발 측의 요청으로 임시로 studium-server 프로젝트의 CORS 정책을 최소화하여,
모든 요청를 allow 하도록 허용합니다.

**Comment by d0lim** [comment]
#60 에 의해 해결된 것으로 보여, 이슈 닫도록 하겠습니다.
추후 조금 더 엄격한 CORS 설정이 필요할 것으로 보이긴 합니다.
