### ISSUE TITLE
성능 차원에서의 Fastify 사용 고려

### ISSUE THREAD

**Issue by selgyun** [TEAM-LEG3ND/studium-server#9]
사용할 수 있는 서버 자원(맥 미니)에 한계가 있기도 하고, nest js가 express와 fastify 모두를 지원하므로 고려해 볼 사항 같습니다.

nest js 공식 문서 소개입니다.
![image](https://github.com/TEAM-LEG3ND/studium-server/assets/29320054/d88274af-4809-4f61-9cbc-e0e687c15029)

**Comment by selgyun** [comment]
참고 사항으로 만약 저희가 파일 업로드를 사용한다면 파일 업로드에 사용하는 Multer package가 Fastify를 지원하지 않는다는 이슈가 있습니다.  https://docs.nestjs.com/techniques/file-upload
![image](https://github.com/TEAM-LEG3ND/studium-server/assets/29320054/0d0101b4-73e8-42de-b377-9819d0f1dd06)

**Comment by d0lim** [comment]
Nest 기능만 사용한다고 하면 괜찮은데, 다른 기능들과 함께 사용하려면 Fastify 자체에 대한 이해도가 조금 필요하긴 합니다.
일단, 저희 프로젝트가 그정도의 성능이 필요한지...도 아직은 의문이구요.
나중에 도메인 단위로 서비스를 쪼개는 상황이 온다면, 그 때 서비스들 별로 사용해보는것은 괜찮을 것 같아요. 모놀리식 프로젝트에서는 아직은 Express가 다양한 경우에 대응하기 좀 더 편한 것 같습니다.

**Comment by selgyun** [comment]
Express 사용으로 이슈 닫겠습니다.
